# Site settings
title: Dara Rouholiman
email: darar@stanford.edu
author: Dara Rouholiman
#description: >

#baseurl: "/darar1.github.io" # Replace with your repo name (e.g., /darar.github.io)
#url: "https://darar1.github.io"

# Social media and professional links
twitter_username: daraRmedicine
github_username: darar1
linkedin_username: darar
google_scholar_username: 6SG4O1YAAAAJ
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
#collections:
  #notes:
    #output: true
    #permalink: /notes/:title/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
  - scope:
      path: ""
    values:
      layout: "default"
